# This file controls the AWS CodeBuild

version: 0.1
phases:
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
  build:
    commands:
    - echo "Entered build phase"
    - npm -i
    - npm i aws-amplify
    - mvn clean prepare-package war:exploded
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - npn run start
    - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*
